version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: message-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: message
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: message-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis-data: